services:
  redis:
    image: redis:6.2.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${DB_PASSWD}
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nanguo

  mysql:
    image: mysql:8.0.42
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - nanguo

  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos
    restart: unless-stopped
    ports:
      - "8848:8848"
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${DB_PASSWD}
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    depends_on:
      - mysql
    networks:
      - nanguo

  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP协议端口
      - "15672:15672" # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest} # 默认用户名（可替换）
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest} # 默认密码（可替换）
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq # 持久化数据
    networks:
      - nanguo

networks:
  nanguo:
    driver: bridge
