version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always 
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nanguo_net 

  mysql:
    image: mysql:latest
    restart: always 
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - nanguo_net 

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - nanguo_net 

networks:
  nanguo_net:
    driver: bridge
