sensors:
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp6_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp3_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp7_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp4_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp8_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp1_input
  - hwmon: /sys/devices/platform/thinkpad_hwmon/hwmon/hwmon6/temp5_input
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon7/temp3_input
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon7/temp4_input
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon7/temp1_input
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon7/temp5_input
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon7/temp2_input
  - hwmon: /sys/devices/virtual/thermal/thermal_zone2/hwmon4/temp1_input
  - hwmon: /sys/devices/virtual/thermal/thermal_zone3/hwmon5/temp1_input
  - hwmon: /sys/devices/virtual/thermal/thermal_zone6/hwmon8/temp1_input
fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0, 60]
  - [1, 60, 65]
  - [2, 65, 70]
  - [3, 70, 75]
  - [4, 75, 80]
  - [5, 80, 255]
